# New Process API Configuration post adding SOAP Prdoducts Proxy"

http.port: "8082"

http_request_sapi:
  host:  "sapi-inventory-vs.us-e2.cloudhub.io"
  path: "/sapi"
  port: "80"
  
http_request_petstore:
  host:  "petstore-VS.us-e2.cloudhub.io"
  path: "/petstore"
  port: "80"
  